- name: Get total IPv6 users
  hosts: huawei_device
  gather_facts: no
  
  tasks:
    - name: Get IPv6 DHCP stats
      community.network.ce_command:
        commands: "display ipv6 dhcp pool statistics"
      register: ipv6_result

    - name: Display result
      debug:
        msg: "{{ ipv6_result }}"
