---
- name: Cisco Playbook - Check ARP for each interface
  hosts: switch1   # match the name in your inventory
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: ATL@nt1$

  tasks:
    - name: Get ARP table
      ios_command:
        commands:
          - show ip arp
      register: arp_output

    - name: Display ARP table
      debug:
        var: arp_output.stdout_lines
