---
- name: Show total IPv6 DHCP users on Huawei routers
  hosts: huawei_routers
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: huawei.vrp.vrp

  tasks:
    - name: Show total IPv6 DHCP users
      huawei.vrp.vrp_command:
        commands:
          - display ipv6 dhcp statistics | include "Total users"
      register: output

    - name: Print/display output
      debug:
        var: output.stdout_lines
