---
- name: Get IPv6 DHCP users
  hosts: your_huawei_device
  gather_facts: no
  
  tasks:
    - name: Get total IPv6 DHCP users
      community.network.ce_command:
        commands:
          - "display ipv6 dhcp pool statistics"
      register: ipv6_result

    - name: Display result
      debug:
        msg: "{{ ipv6_result }}"
